# This is a basic workflow to help you get started with Actions

name: dummy manual workflow

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      VERSION:
        description: "my version as input"
        required: true
        default: "aanajbsajsa"

defaults:
  run:
    shell: pwsh

env:
  VERSION: ${{ github.event.inputs.VERSION }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run my PS script
        run: ls /usr/share/

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo input:VERSION ${{ env.VERSION }}

      - name: setting a variable
        run: |
          $ver = @(678) | sort-object -Top 1
          "someVar=$ver" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
          
#       - name: getting the variable
#         run: echo "someVar:" ${{ env.someVar }}
        
      - name: getting the repo name
        if: env.someVar != ''
        shell: bash
        run: |
          echo ${GITHUB_REPOSITORY}
          echo ${GITHUB_ACTOR}
        
