name: simple test workflow

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  infoJob:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          echo "Hello World!!!"
          Get-Module -Name "Az.Accounts" -ListAvailable
