name: simple test workflow

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  infoJob:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          $stime = Get-Date -DisplayHint Time
          (New-Object System.Net.WebClient).DownloadFile("https://vstsagenttools.blob.core.windows.net/tools/demoAssets/test/dotnet_sdk.zip", "dnetsdk.zip")
          $diff = (Get-Date -DisplayHint Time) - $stime
          $diff
